repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--settings-file",".isort.cfg","--profile", "black" ]
  - repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3
  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        args: [ "--in-place", "--wrap-summaries", "88", "--wrap-descriptions", "88" ]
