"""add band number.

Revision ID: 1c26034449b9
Revises: 9505cfab1f85
Create Date: 2023-05-13 20:32:34.412577
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1c26034449b9"
down_revision = "9505cfab1f85"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "release_canary_band", sa.Column("band_number", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("release_canary_band", "band_number")
    # ### end Alembic commands ###
