"""change canary period type.

Revision ID: 33873c5a7bbe
Revises: d1b816f53004
Create Date: 2023-05-05 15:49:31.100669
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "33873c5a7bbe"
down_revision = "d1b816f53004"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "release",
        "canary_period",
        existing_type=sa.NUMERIC(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "release",
        "canary_period",
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
