"""add is_canary to signal.

Revision ID: 652e9c47c653
Revises: 9261790e46ac
Create Date: 2023-05-28 14:55:01.811426
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "652e9c47c653"
down_revision = "9261790e46ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("signal", sa.Column("is_canary", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("signal", "is_canary")
    # ### end Alembic commands ###
