"""add signal period column.

Revision ID: 738957fcc3bc
Revises: 9dbfd3ac874b
Create Date: 2023-04-30 15:33:22.382549
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "738957fcc3bc"
down_revision = "9dbfd3ac874b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("signal", sa.Column("created_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("signal", "created_date")
    # ### end Alembic commands ###
