"""add release status columns.

Revision ID: 84a61d063ad6
Revises: 5a588045e274
Create Date: 2023-04-30 14:16:05.993738
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "84a61d063ad6"
down_revision = "5a588045e274"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("release", sa.Column("is_canary", sa.Boolean(), nullable=True))
    op.add_column("release", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("release", "is_active")
    op.drop_column("release", "is_canary")
    # ### end Alembic commands ###
