"""refactor bands.

Revision ID: 9505cfab1f85
Revises: 5bb75e0be87b
Create Date: 2023-05-13 16:29:05.937050
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9505cfab1f85"
down_revision = "aebc398fc592"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("release", sa.Column("band_count", sa.Integer(), nullable=True))
    op.drop_column("release_canary_band", "duration")
    op.drop_column("release_canary_band", "is_active")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "release_canary_band",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "release_canary_band",
        sa.Column("duration", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("release", "band_count")
    # ### end Alembic commands ###
