"""add release period columns.

Revision ID: 9dbfd3ac874b
Revises: 84a61d063ad6
Create Date: 2023-04-30 14:43:49.077569
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9dbfd3ac874b"
down_revision = "84a61d063ad6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("release", sa.Column("threshold", sa.Numeric(), nullable=True))
    op.add_column("release", sa.Column("canary_period", sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("release", "canary_period")
    op.drop_column("release", "threshold")
    # ### end Alembic commands ###
